### ISSUE TITLE
problem with setTaggedValue

### ISSUE THREAD

**Issue by AndreaCodd** [esys-escript/esys-escript.github.io#13]
There is a problem with setTaggedValue.  It does not seem to be working.

**Comment by LutzGross** [comment]
Can you be a bot more specific? Example?

**Comment by AndreaCodd** [comment]
The output from

dom = finley.ReadGmsh("Kalgoorlie_Gravity_201x338b.msh", numDim=3)
w_e = escript.Scalar(0, escript.Function(dom))        
w_e.setTaggedValue("DataArea",1)
w_e.expand()
print('w_e')
print(w_e)

is

w_e
Summary: inf=0 sup=0 data points=1020688

**Comment by LutzGross** [comment]
what does `dom.showTagNames()` say?

**Comment by AndreaCodd** [comment]
Air, Base, BottomFace, DataArea, PaddingAir, PaddingBase, TopFace

**Comment by LutzGross** [comment]
You can get the tag number by `dom.getTag('DataArea')` and check if this is actually being used `escript.Function(dom).getListOfTags()`.

**Comment by AndreaCodd** [comment]
dom.showTagNames():     Air, Base, BottomFace, DataArea, PaddingAir, PaddingBase, TopFace
dom.getTag('DataArea'):    1
escript.Function(dom).getListOfTags():    [3]
dom.isValidTagName('DataArea'):   True

**Comment by LutzGross** [comment]
'escript.Function(dom).getListOfTags(): [3]' tells you that there are no elements in the mesh with 'DataArea'=1 tag.

**Comment by AndreaCodd** [comment]
The mesh and code worked fine last April.

**Comment by AndreaCodd** [comment]
Ok.  I copied an old mesh file from my work PC. and it worked.  so I suppose I need to use an older version of gmsh.

**Comment by LutzGross** [comment]
I believe that you can set the format version when you generate the msh file. it should be 2.2 or lower.
