### ISSUE TITLE
atan2 is not consistent with arctan2 of numpy

### ISSUE THREAD

**Issue by LutzGross** [esys-escript/esys-escript.github.io#16]
atan2(X,Y) should be 
X>0 Y>0 = 0 to 90 (in rad)    (is correct)
X>0 Y<0 = 90 to 180          (is *incorrect*)
X <0, Y>0 = 0 to -90        (is correct)
X<0 Y<0 = -90 to -180    (is i*ncorrect*)

**Comment by LutzGross** [comment]
This could provide a fix in util.atan2
   
s=atan(arg0/(arg1+m))*(1-m)+(np.pi/2)*(1-2*m2)* m
s+=(wherePositive(arg0)*whereNegative(arg1)-whereNegative(arg0)*whereNegative(arg1))*np.pi

but maybe this can be implemented better.

**Comment by LutzGross** [comment]
A better version:

z1=whereZero(arg1, rtol=EPSILON)
s=(atan(arg0/(arg1+z1)) + sign(arg0)*whereNegative(arg1)*np.pi )*(1-z1)+sign(arg0)*whereNegative(arg1)*np.pi/2*z1

**Comment by aellery** [comment]
I have fixed this.
