### ISSUE TITLE
downunder: Stopping criteria for LBFGS

### ISSUE THREAD

**Issue by aellery** [esys-escript/esys-escript.github.io#50]
We need more control over the stopping criteria in LBFGS.

I would like to be able to stop iterating and output the answer for the following

1. |J_k - J_0| < jtol_1
2. misfit only criteria
3. max number of iterations gives you the answer rather than killing itself.

**Comment by LutzGross** [comment]
downunder as been removed and BFGS has been implemented in  esys.escript.minimizers
