### ISSUE TITLE
ripley: tagging on Dirac points does not work 

### ISSUE THREAD

**Issue by LutzGross** [esys-escript/esys-escript.github.io#63]
this is because there is no implementation for borrowListOfTagsInUse for this data type.

**Comment by LutzGross** [comment]
One of the test failing is 

 test_interpolateC_DiracDeltaFunctions_fromData_ContinuousFunction_expanded_rank0 ((run_utilOnRipley.Test_2D_Point_Data_Interpolation)

**Comment by aellery** [comment]
This feature has been added and the test now passes.
