### ISSUE TITLE
imp module is deprecated 

### ISSUE THREAD

**Issue by LutzGross** [esys-escript/esys-escript.github.io#7]
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat

**Comment by aellery** [comment]
Do you know which file is still using the imp module? I'm having trouble locating it with grep.

**Comment by LutzGross** [comment]
Maybe it is not a escript problem but related to external python packages. This would not be numpy, scipy or matplot lib as I don;t get the problem when I load these. maybe gdal?

**Comment by LutzGross** [comment]
fixed
