### ISSUE TITLE
convertToNumpy does not work for more than 1 data point per elemen

### ISSUE THREAD

**Issue by LutzGross** [esys-escript/esys-escript.github.io#71]
domain=Rectangle(l0=1, l1=1, n0=10, n1=10)
u=domain.get(x)[0]
g=grad(u)
g_np=convertToNump(g)
assert g_np.shape == (10*10*4, 2)

but  it is g_np.shape == (10*10, 2)

**Comment by aellery** [comment]
Did you mean 
x=domain.getX()
u=x[0]
g=grad(u)

In this example, does g have 400 data points?

**Comment by AndreaCodd** [comment]
u=domain.getX[0]

is probably what Lutz meant to write as his second line.

**Comment by aellery** [comment]
Fixed in the latest commit.
