### ISSUE TITLE
Version 6.0 unit testing

### ISSUE THREAD

**Issue by aellery** [esys-escript/esys-escript.github.io#80]
The unit testing in branch 6.0 currently fails because the testing program starts looking for a library file that doesn't exist (build/posix/escriptcore/src/libescript.so).

**Comment by LutzGross** [comment]
I had to change Scons script slightly to make it work for SCons: v4.4.0 on MacOS.

**Comment by aellery** [comment]
I was wrong in my original post. The library file does exist if you do a build from scratch but the unit testing returns an ImportError when running the script run_units.py.

**Comment by aellery** [comment]
Fixed in the latest commit.
